#!/bin/sh
set -e -u

curl -s https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/ | grep '<a *class="panel-block.*"*href=".*fx\.tar\.xz".*>$' \
	| sed 's/.\+href="\(.\+\)"\s\+style.*>/\1/g' \
	| sed 's#\./\(.\+\)/fx\.tar\.xz#\1#g' \
	| sort \
	| jq --raw-input --slurp '[split("\n") | map(select(. != "")) | .[] | {build: .}]'
